### ISSUE TITLE
Should this plugin check which zone to use first?

### ISSUE THREAD

**Issue by jaredcdep** [caddy-dns/rfc2136#7]
I am currently using dehydrated with nsupdate to add the acme challenge record. 

I am trying to get caddy working with the rfc2136 plugin

The problem is `_acme-challenge.ldn.example.net` is its own zone on the dns server so that we can allow remote updates only on that zone , and the plugin is trying to update the record on the `ldn.example.net` zone where updates are not allowed. 

nsupdate seems to query the dns server first for the SOA to establish the zone name that the record should be in. 

I am going through the rfc2136 docs to try see which behaviour is correct.

**Comment by jaredcdep** [comment]
As I assume this is a wrapper for https://github.com/libdns/rfc2136 I am cross posting there

**Comment by KoHcoJlb** [comment]
This plugin receives zone name from Caddy, which should already be doing [SOA discovery](https://github.com/caddyserver/certmagic/blob/4293198e094ded561f69e2fc3df49d53c3c5cb89/solvers.go#L382).
Does your dns server return correct SOA record for `_acme-challenge.ldn.example.net`?
Also, Caddy here could be talking to another dns server, because this is controlled by another settings, which does not return correct SOA for this domain.

**Comment by jaredcdep** [comment]
Thanks for that tip , Ill investigate the caddy discovery and update here 

I have tried specifying resolvers as per https://github.com/caddy-dns/rfc2136/issues/4

**Comment by jaredcdep** [comment]
Just an update:

Quite silly of me , I realised the resolver I was using actually provides a different `ldn.example.net` SOA as its our internal active directory. 

Unfortunately, I still seem to be having issues  
I have enabled debug log to investigate, but I don't seem to be getting any logs from certmagic you pointed me to , and from the caddy-dns process

But I think since this probably isn't relevant to this plugin I should move to the Caddy community forum

Thanks for the help!
